_target_: pepo.trainer.deppo.DEPPOTrainer
_partial_: true
train_batch_size: 4
eval_batch_size: 32
gradient_accumulation_steps: 1
early_stopping_patience: null
early_stopping_min_delta: 0.001

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  fused: true

scheduler_name: cosine
scheduler_num_warmup_steps: 0

wandb_config: ${wandb}
