_target_: pepo.trainer.SingleModelTrainer
_partial_: true
gradient_accumulation_steps: 1
early_stopping_patience: null
early_stopping_min_delta: 0.001
log_interval: 1
skip_eval: false
max_batches_per_epoch: null
force: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  fused: true

scheduler_name: cosine
scheduler_num_warmup_steps: 0

wandb_config: ${wandb}
