[project]
name = "PEPO"
version = "0.1.0"
requires-python = "==3.13.*" # Locks to the Python you used

# Define all your project's dependencies
dependencies = [
    "torch",
    "peft",
    "transformers",
    "accelerate",
    "hydra-core",
    "datasets<4.0.0",
    "python-dotenv",
    "numpy", # To fix that warning
    "jupyter>=1.1.1",
    "wandb>=0.23.0",
    "alpaca-eval>=0.6.6",
    "setuptools<81",
    "bitsandbytes>=0.48.2",
]

[tool.uv]
[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
# This is important! It tells uv to *only* look for
# packages we specify in [tool.uv.sources] here.
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
alpaca-eval = { path = "./alpaca_eval", editable = true }

[dependency-groups]
dev = [
    "detect-secrets",
    "mypy[faster-cache]>=1.17.1",
    "pytest>=8.4.2",
    "ruff>=0.1.0",
    "pre-commit>=4.3.0",
    "nb-clean>=4.0.0",
    "types-tqdm>=4.67.0.20250809",
    "pandas-stubs>=2.3.3.251201",
    "types-pyyaml>=6.0.12.20250915",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.13"
strict=true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
exclude = [
    "alpaca_eval",
    "arena-hard-auto",
    "LLM",
    "figures"
]

[[tool.mypy.overrides]]
module = [
    "alpaca_eval.*",
    "transformers.*",
    "peft.*",
    "accelerate.*",
    "bitsandbytes.*",
    "wandb.*",
    "hydra.*"
]
ignore_missing_imports = true
follow_imports = "skip"
