[project]
name = "PEPO"
version = "0.1.0"
requires-python = "==3.13.*" # Locks to the Python you used

# Define all your project's dependencies
dependencies = [
    "torch",
    "peft",
    "transformers",
    "accelerate",
    "hydra-core",
    "datasets<4.0.0",
    "python-dotenv",
    "numpy", # To fix that warning
    "jupyter>=1.1.1",
    "wandb>=0.23.0",
    "alpaca-eval[vllm]>=0.6.6",
]

[tool.uv]
[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
# This is important! It tells uv to *only* look for
# packages we specify in [tool.uv.sources] here.
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }

[dependency-groups]
dev = [
    "detect-secrets",
    "pre-commit",
    "types-pyyaml>=6.0.12.20250915",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
