defaults:
  - /trainer@trainer: single
  - /generator@generator: greedy
  - _self_

_target_: pepo.model.sfdeppo.SFDEPPOModel
backbone: ${backbone}
num_networks: 1

wandb:
  tags: ["sfdeppo"]

debug: ${debug}
beta: 0.1
sft_weight: 1.0

trainer:
  training_epochs: 1

generator:
  batch_size: ${backbone.generator_batch_size}
