defaults:
  - /trainer@trainer: single
  - /generator@generator: greedy
  - _self_

_target_: pepo.model.sftdpo.SFTDPOModel
backbone: ${backbone}

wandb:
  tags: ["sftdpo"]

debug: ${debug}
beta: 0.1
sft_weight: 0.005

trainer:
  training_epochs: 1
