# Greedy Sampling Generator Configuration
_target_: pepo.generator.Generator

use_ensamble: true
greedy_sampling: true

max_new_tokens: 1024
batch_size: 10 # usually overridden by model config (depends on the model size)

top_p_sampling: false
temperature: 1.0
top_p: 0.9
