# Top-p Sampling Generator Configuration
_target_: pepo.generate.Generator

max_new_tokens: 512
use_ensamble: true
batch_size: 10
greedy_sampling: false
top_p_sampling: true
temperature: 1.0
top_p: 0.9
