# PEPO Ensemble Training Configuration
defaults:
  - model: llama_instruct
  # - model: smollm
  - hub: default
  - device: default
  - _self_

model:
  num_networks: ${L}

# Reproducibility
seed: 42

log_level: "info"  # Options: "debug", "info", "warning", "error", "critical" (case-insensitive)

L: 4 # Number of submodels in the ensemble
