# General Evaluation Configuration
defaults:
  - model: llama_instruct
  - evaluator: alpaca
  - hub: eval
  - device: default
  - _self_

model:
  num_networks: ${L}

evaluator:
  num_samples: ${num_samples}
  output_dir: ${output_dir}

hub:
  load: true
  push: false

log_level: "info"  # Options: "debug", "info", "warning", "error", "critical" (case-insensitive)

L: 4 # Number of submodels in the ensemble

output_dir: "eval_outputs"  # Directory to save generated responses (relative to project root)
force_generate: false  # If true, regenerate responses even if they exist
num_samples: null # null = use full dataset
max_new_tokens: 1000
batch_size: 100
epochs: 2

seed: 42
